apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: nginx-pv
spec:
  containers:
  - image: nginx
    name: nginx-pv
    volumeMounts:
    - name: nginx-pv
      mountPath: /data
  volumes:
    - name: nginx-pv
      persistentVolumeClaim:
        claimName: nginx-pvc
