apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:  
  namespace: development  
  name: developer
rules:
- apiGroups: [""]  
  resources: ["pods"]  
  verbs: ["get", "list", "get", "update", "delete"]
