apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null  labels:    run: redis-storage  name: redis-storage
spec:
  containers:
  - image: redis:alpine
    name: redis-storage
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
